name = "databricks-keepalive-worker"
main = "_worker.js"
compatibility_date = "2025-10-22"

# 如果使用 environment variables，请在 Cloudflare Dashboard 或 Wrangler secrets 中设置
# 例如： wrangler secret put DATABRICKS_TOKEN
